
DROP TABLE OWNER CASCADE CONSTRAINTS;

DROP TABLE OWNER_EMAIL_VERIFICATION CASCADE CONSTRAINTS;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

DROP TABLE DOCUMENT CASCADE CONSTRAINTS;

DROP TABLE CUSTOMER_EMAIL_VERIFICATION CASCADE CONSTRAINTS;

DROP TABLE CYCLE CASCADE CONSTRAINTS;

DROP TABLE OWNS CASCADE CONSTRAINTS;

DROP TABLE TRIP_DETAILS CASCADE CONSTRAINTS;

DROP TABLE CYCLE_REVIEW CASCADE CONSTRAINTS;

DROP TABLE PEER_REVIEW CASCADE CONSTRAINTS;

DROP TABLE RESERVES CASCADE CONSTRAINTS;

DROP TABLE ADMIN CASCADE CONSTRAINTS;

DROP SEQUENCE OWNER_INCREMENT;
DROP SEQUENCE CUSTOMER_INCREMENT;
DROP SEQUENCE CYCLE_INCREMENT;
DROP SEQUENCE TRIP_INCREMENT;
DROP SEQUENCE CYCLE_REVIEW_INCREMENT;
DROP SEQUENCE PEER_REVIEW_INCREMENT;
DROP SEQUENCE ADMIN_INCREMENT;